# fly.toml app configuration file for CampusNex
#
# See https://fly.io/docs/reference/configuration/ for information

app = "campusnex"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[env]
  NODE_ENV = "production"
  PORT = "5000"
