name: campusnex_app
description: "A production-grade multi-tenant offline-first digital campus client for CampusNex."
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  http: ^1.1.0
  sqflite: ^2.3.0
  path: ^1.8.3
  uuid: ^4.2.0
  web_socket_channel: ^2.4.1
  shared_preferences: ^2.2.2
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
